---
title: "lab05_Antunes"
author: "Danilo Antunes"
format: html
---

# Lab 05

```{r}
library(tidyverse)
library(ggplot2)
library(leaflet)
library(ggcal)

analisa_aeronave <- function(tail_number, arquivo) {
  
  # importação dos dados
  getStats <- function(input, pos) {
    input %>% 
    filter(TAIL_NUMBER == tail_number) %>% 
    filter(
      !is.na(YEAR),
      !is.na(MONTH),
      !is.na(DAY),
      !is.na(TAIL_NUMBER),
      !is.na(ORIGIN_AIRPORT),
      !is.na(DESTINATION_AIRPORT),
      !is.na(DEPARTURE_TIME)
    ) %>%
    filter(!(substr(DESTINATION_AIRPORT, 1, 1) == "1")) %>%
    arrange(YEAR, MONTH, DAY, DEPARTURE_TIME) 
  }

  dados = read_csv_chunked(
    arquivo, 
    callback=DataFrameCallback$new(getStats), 
    chunk_size = 1e5
  )

  airports <- read_csv("datasets/airports.csv")
  
  # unindo os dois datasets
  dados_mapa <- dados %>% 
    left_join(
      airports %>% select(IATA_CODE, LATITUDE, LONGITUDE, AIRPORT, CITY), 
      by = c("ORIGIN_AIRPORT" = "IATA_CODE")
    ) %>% 
    rename(lat_orig = LATITUDE, 
           lng_orig = LONGITUDE, 
           nome_orig = AIRPORT, 
           cidade_orig = CITY) %>%
    left_join(
      airports %>% select(IATA_CODE, LATITUDE, LONGITUDE, AIRPORT, CITY),
      by = c("DESTINATION_AIRPORT" = "IATA_CODE")
    ) %>%
    rename(lat_dest = LATITUDE, 
           lng_dest = LONGITUDE, 
           nome_dest = AIRPORT, 
           cidade_dest = CITY) %>%
    filter(!is.na(lat_orig), !is.na(lng_orig), !is.na(lat_dest), !is.na(lng_dest)) %>%
    mutate(
      # adicionando coluna de velocidade
      AIR_TIME = as.numeric(AIR_TIME),
      DISTANCE = as.numeric(DISTANCE),
      velocidade_mph = ifelse(
          !is.na(AIR_TIME) & AIR_TIME > 0, 
          DISTANCE / (AIR_TIME / 60), 
          NA
        )
    )
  
  # criando o mapa
  
  cores <- colorNumeric(
    palette = "YlOrRd", 
    domain = dados_mapa$velocidade_mph, 
    na.color = "#2b5c8f"
  )

  mapa <- leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron)

  for (i in seq_len(nrow(dados_mapa))) {
    row <- dados_mapa[i, ]
    
    espessura <- 0.01 + (row$velocidade_mph / 100)
    cor_linha <- cores(row$velocidade_mph)
    
    popup_txt <- paste0(
      "<b>Trecho #</b>", i, "<br/>",
      "<b>Data:</b> ", sprintf("%02d/%02d/%04d", row$DAY, row$MONTH, row$YEAR), "<br/>",
      "<b>Voo:</b> ", row$AIRLINE, " ", row$FLIGHT_NUMBER, "<br/>",
      "<b>Trajeto:</b> ", row$ORIGIN_AIRPORT, " ➔ ", row$DESTINATION_AIRPORT, "<br/>",
      "<b>Distância:</b> ", row$DISTANCE, " milhas<br/>",
      "<b>Velocidade Média:</b> ", paste0(round(row$velocidade_mph, 1), " mph")
    )

    mapa <- mapa %>%
      addPolylines(
        lng = c(row$lng_orig, row$lng_dest),
        lat = c(row$lat_orig, row$lat_dest),
        weight = espessura,
        color = cor_linha,
        opacity = 0.6,
        popup = popup_txt
      )
  }
  
  # adicionando os aeroportos visitados ao mapa
  airports_visitados <- bind_rows(
    dados_mapa %>% select(IATA_CODE = ORIGIN_AIRPORT, 
                          LATITUDE = lat_orig, 
                          LONGITUDE = lng_orig, 
                          NOME = nome_orig, 
                          CIDADE = cidade_orig),
    dados_mapa %>% select(IATA_CODE = DESTINATION_AIRPORT, 
                          LATITUDE = lat_dest, 
                          LONGITUDE = lng_dest, 
                          NOME = nome_dest, 
                          CIDADE = cidade_dest)
  ) %>% distinct(IATA_CODE, .keep_all = TRUE)
  
  mapa <- mapa %>%
    addCircleMarkers(
      data = airports_visitados,
      lng = ~LONGITUDE,
      lat = ~LATITUDE,
      radius = 4,
      color = "#1d3557",
      fillColor = "#457b9d",
      fillOpacity = 0.9,
      weight = 1.5,
      popup = ~paste0("<b>", IATA_CODE, "</b> - ", NOME, "<br/>", CIDADE)
    ) %>%
    addLegend(
      pal = cores,
      values = dados_mapa$velocidade_mph,
      title = "Velocidade (mph)",
      position = "bottomright"
    )
  
  return(list(
    tabela = dados,
    mapa = mapa
  ))
}
```

```{r}
arquivo <- file.path("datasets", "flights.csv.zip")

res <- analisa_aeronave("N431WN", arquivo)

res$tabela
res$mapa
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```







